# Generated by Django 5.1.4 on 2024-12-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20241209_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
